#ifndef GAME
#define GAME
void game_fsm_run(void);

typedef enum {
	STATE_CONFIGURE_MENU,
	STATE_CONFIGURE_NAME,
	STATE_CONFIGURE_WIDTH,
	STATE_CONFIGURE_HEIGHT,
	STATE_CONFIGURE_SNAKE_SPEED
} GameConfigureState;

typedef enum {
	STATE_SELECTED_WIDTH,
	STATE_SELECTED_HEIGHT,
	STATE_SELECTED_SNAKE_SPEED
} GameConfigureSelectedState;

#endif
